apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"date-ip"},"name":"date-ip-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"date-ip-pod"}},"template":{"metadata":{"labels":{"app":"date-ip-pod"}},"spec":{"containers":[{"image":"timbbishop/date-ip","name":"date-ip","ports":[{"containerPort":3000}]}]}}}}
  creationTimestamp: "2021-10-05T20:37:22Z"
  generation: 1
  labels:
    app: date-ip
  name: date-ip-deployment
  namespace: default
  resourceVersion: "1666770"
  uid: 6bdf023a-0018-45a9-868b-ab04a6223fa0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: date-ip-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: date-ip-pod
    spec:
      containers:
      - image: timbbishop/date-ip
        imagePullPolicy: Always
        name: date-ip
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-05T20:37:25Z"
    lastUpdateTime: "2021-10-05T20:37:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-05T20:37:22Z"
    lastUpdateTime: "2021-10-05T20:37:25Z"
    message: ReplicaSet "date-ip-deployment-bcffc4848" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
